name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        env:
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1

      - name: Run typecheck
        run: pnpm ts:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        env:
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1

      - name: Run linter
        run: |
          pnpm check
        env:
          SKIP_ENV_VALIDATION: true

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        env:
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1

      - name: Run all tests
        run: pnpm test
        env:
          SKIP_ENV_VALIDATION: true

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        env:
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1

      - name: Deploy migrations to database
        run: pnpx prisma migrate deploy
        env:
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
        if: |
          github.event_name != 'pull_request' && github.ref != 'refs/heads/develop'

      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Build application
        run: pnpm build
        env:
          SKIP_ENV_VALIDATION: true
